services:
  web:
    build: ./webapp
    ports:
      - "8080:80"
    networks:
      - web-network
    depends_on:
      - go
  go:
    build: ./src
    networks:
      - web-network
      - db-network
    depends_on:
      - postgres
  #    - redis
  # uses port 5432
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db-network
  # uses port 6379
  #redis:
  #  image: redis
  #  networks:
  #    - db-network

networks:
  web-network:
  db-network: